import { User } from '../types';
import { MODERN_EMPTY_AVATAR_DATA_URI } from '../components/common/ModernAvatar';

export const INITIAL_CREATORS: User[] = [
  {
    id: 'user_icedrick444',
    name: 'Icedrick',
    username: 'icedrick',
    avatar: MODERN_EMPTY_AVATAR_DATA_URI,
    bannerUrl: '',
    bio: 'Lead Creator & Engineer · Building calm, tactile social technology on Aura.',
    pronouns: 'they/them',
    location: 'Kigali, Rwanda',
    website: 'https://sodanox.ai.studio',
    joinedDate: 'Joined September 2026',
    followersCount: 384,
    followingCount: 88,
    followers: [],
    following: [],
    isFollowing: false,
    isFollower: false,
    isMutual: false,
    verified: true,
    email: 'icedrick444@gmail.com',
    privateAccount: false,
    themePreference: 'nordic',
    allowMessagesFrom: 'everyone',
    showOnlineStatus: true,
    allowReshare: true,
  },
  {
    id: 'Xu0Rc4W9fZgpjh0bEWzEvxbN4pC2',
    name: 'Raphaël NSHIMYUMUKIZA',
    username: 'raphael_nsh',
    avatar: MODERN_EMPTY_AVATAR_DATA_URI,
    bannerUrl: '',
    bio: 'Architectural designer & spatial researcher · Rammed earth, light, and contemplative structures in Kigali.',
    pronouns: 'he/him',
    location: 'Kigali, Rwanda',
    website: 'https://github.com/reponsekdz3',
    joinedDate: 'Joined September 2026',
    followersCount: 142,
    followingCount: 38,
    followers: [],
    following: [],
    isFollowing: false,
    isFollower: false,
    isMutual: false,
    verified: true,
    email: 'raphanshimyumukiza@gmail.com',
    privateAccount: false,
    themePreference: 'nordic',
    allowMessagesFrom: 'everyone',
    showOnlineStatus: true,
    allowReshare: true,
  },
  {
    id: 'user_reponsekdz01',
    name: 'Reponse KDZ',
    username: 'reponsekdz',
    avatar: MODERN_EMPTY_AVATAR_DATA_URI,
    bannerUrl: '',
    bio: 'Lead Engineer & Founder · Building calm, tactile social technology on Aura.',
    pronouns: 'he/him',
    location: 'Kigali, Rwanda',
    website: 'https://github.com/reponsekdz3',
    joinedDate: 'Joined September 2026',
    followersCount: 284,
    followingCount: 64,
    followers: [],
    following: [],
    isFollowing: false,
    isFollower: false,
    isMutual: false,
    verified: true,
    email: 'reponsekdz01@gmail.com',
    privateAccount: false,
    themePreference: 'nordic',
    allowMessagesFrom: 'everyone',
    showOnlineStatus: true,
    allowReshare: true,
  },
  {
    id: 'user_clara_mugabo',
    name: 'Clara Mugabo',
    username: 'claramugabo',
    avatar: MODERN_EMPTY_AVATAR_DATA_URI,
    bannerUrl: '',
    bio: 'Acoustic artist & field recordist · Capturing organic soundscapes across the Great Lakes region.',
    pronouns: 'she/her',
    location: 'Lake Kivu & Kigali, Rwanda',
    website: 'https://claramugabo.sound',
    joinedDate: 'Joined September 2026',
    followersCount: 198,
    followingCount: 42,
    followers: [],
    following: [],
    isFollowing: false,
    isFollower: false,
    isMutual: false,
    verified: true,
    email: 'clara@aurasocial.org',
    privateAccount: false,
    themePreference: 'nordic',
    allowMessagesFrom: 'everyone',
    showOnlineStatus: true,
    allowReshare: true,
  },
  {
    id: 'user_marcus_v',
    name: 'Marcus Vianna',
    username: 'marcus_v',
    avatar: MODERN_EMPTY_AVATAR_DATA_URI,
    bannerUrl: '',
    bio: 'Ceramicist & industrial form designer · Nordic stoneware & organic glazes.',
    pronouns: 'he/him',
    location: 'Oslo / Kigali',
    website: 'https://marcusvianna.studio',
    joinedDate: 'Joined September 2026',
    followersCount: 165,
    followingCount: 51,
    followers: [],
    following: [],
    isFollowing: false,
    isFollower: false,
    isMutual: false,
    verified: true,
    email: 'marcus@aurasocial.org',
    privateAccount: false,
    themePreference: 'nordic',
    allowMessagesFrom: 'everyone',
    showOnlineStatus: true,
    allowReshare: true,
  },
];

/**
 * Initializes Firestore with community data if requested.
 * Pure application mode: No mock or demo data seeded to keep the platform clean for real users.
 */
export async function seedCommunityDataIfEmpty(_currentUser?: User): Promise<void> {
  // Pure genuine platform: No demo or mock users/data seeded into Firestore
  return;
}
