import { User } from '../types';

export const INITIAL_CREATORS: User[] = [
  {
    id: 'Xu0Rc4W9fZgpjh0bEWzEvxbN4pC2',
    name: 'Raphaël NSHIMYUMUKIZA',
    username: 'raphael_nsh',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=400&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1200&q=80',
    bio: 'Architectural designer & spatial researcher · Rammed earth, light, and contemplative structures in Kigali.',
    pronouns: 'he/him',
    location: 'Kigali, Rwanda',
    website: 'https://github.com/reponsekdz3',
    joinedDate: 'Joined September 2026',
    followersCount: 142,
    followingCount: 38,
    followers: [],
    following: [],
    isFollowing: false,
    isFollower: false,
    isMutual: false,
    verified: true,
    email: 'raphanshimyumukiza@gmail.com',
    privateAccount: false,
    themePreference: 'nordic',
    allowMessagesFrom: 'everyone',
    showOnlineStatus: true,
    allowReshare: true,
  },
  {
    id: 'user_reponsekdz01',
    name: 'Reponse KDZ',
    username: 'reponsekdz',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=400&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=1200&q=80',
    bio: 'Lead Engineer & Founder · Building calm, tactile social technology on Aura.',
    pronouns: 'he/him',
    location: 'Kigali, Rwanda',
    website: 'https://github.com/reponsekdz3',
    joinedDate: 'Joined September 2026',
    followersCount: 284,
    followingCount: 64,
    followers: [],
    following: [],
    isFollowing: false,
    isFollower: false,
    isMutual: false,
    verified: true,
    email: 'reponsekdz01@gmail.com',
    privateAccount: false,
    themePreference: 'nordic',
    allowMessagesFrom: 'everyone',
    showOnlineStatus: true,
    allowReshare: true,
  },
  {
    id: 'user_clara_mugabo',
    name: 'Clara Mugabo',
    username: 'claramugabo',
    avatar: 'https://images.unsplash.com/photo-1531746020798-e6953c6e8e04?auto=format&fit=crop&w=400&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1518495973542-4542c06a5843?auto=format&fit=crop&w=1200&q=80',
    bio: 'Acoustic artist & field recordist · Capturing organic soundscapes across the Great Lakes region.',
    pronouns: 'she/her',
    location: 'Lake Kivu & Kigali, Rwanda',
    website: 'https://claramugabo.sound',
    joinedDate: 'Joined September 2026',
    followersCount: 198,
    followingCount: 42,
    followers: [],
    following: [],
    isFollowing: false,
    isFollower: false,
    isMutual: false,
    verified: true,
    email: 'clara@aurasocial.org',
    privateAccount: false,
    themePreference: 'nordic',
    allowMessagesFrom: 'everyone',
    showOnlineStatus: true,
    allowReshare: true,
  },
  {
    id: 'user_marcus_v',
    name: 'Marcus Vianna',
    username: 'marcus_v',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=400&q=80',
    bannerUrl: 'https://images.unsplash.com/photo-1493976040374-85c8e12f0c0e?auto=format&fit=crop&w=1200&q=80',
    bio: 'Ceramicist & industrial form designer · Nordic stoneware & organic glazes.',
    pronouns: 'he/him',
    location: 'Oslo / Kigali',
    website: 'https://marcusvianna.studio',
    joinedDate: 'Joined September 2026',
    followersCount: 165,
    followingCount: 51,
    followers: [],
    following: [],
    isFollowing: false,
    isFollower: false,
    isMutual: false,
    verified: true,
    email: 'marcus@aurasocial.org',
    privateAccount: false,
    themePreference: 'nordic',
    allowMessagesFrom: 'everyone',
    showOnlineStatus: true,
    allowReshare: true,
  },
];

/**
 * Initializes Firestore with community data if requested.
 * Pure application mode: No mock or demo data seeded to keep the platform clean for real users.
 */
export async function seedCommunityDataIfEmpty(_currentUser?: User): Promise<void> {
  // Pure genuine platform: No demo or mock users/data seeded into Firestore
  return;
}
